CREATE TABLE IF NOT EXISTS EMPLOYEE (ID CHAR(3) PRIMARY KEY, NAME CHAR(30), SALARY DECIMAL(12,2), DEPT CHAR(10));
INSERT INTO EMPLOYEE VALUES ('WSM', 'William Shakespeare',  20000, 'Markets');
INSERT INTO EMPLOYEE VALUES ('ACM', 'Agatha Christie', 20000, 'Markets');
INSERT INTO EMPLOYEE VALUES ('JKH', 'J. K. Rowling', 5000, 'HHRR');
INSERT INTO EMPLOYEE VALUES ('ATH', 'Akira Toriyama', 2980, 'HHRR');
INSERT INTO EMPLOYEE VALUES ('SKS', 'Stephen King',  3000, 'Sales');
INSERT INTO EMPLOYEE VALUES ('JRS', 'J. R. R. Tolkien', 2000, 'Sales');
